name: Trigger Make Webhook Monthly

on:
  schedule:
    - cron: '59 14 28-31 * *' # 매달 말일 밤 11:59 (한국시간 기준, UTC 14:59)
  workflow_dispatch:  # 수동 실행도 가능하게

jobs:
  trigger_webhook_monthly:
    runs-on: ubuntu-latest

    steps:
    - name: Call Make Webhook Monthly
      run: |
        curl -X POST "${{ secrets.MAKE_WEBHOOK_URL_MONTHLY }}"