name: Trigger Make Webhook Yearly

on:
  schedule:
    - cron: '59 14 31 12 *' # 매년 12월 31일 한국시간 23:59 기준 (UTC 14:59)
  workflow_dispatch:  # 수동 실행 가능

jobs:
  trigger_webhook_yearly:
    runs-on: ubuntu-latest

    steps:
    - name: Call Make Webhook Yearly
      run: |
        curl -X POST "${{ secrets.MAKE_WEBHOOK_URL_YEARLY }}"
