name: Trigger Make Webhook for Yearly

on:
  schedule:
    - cron: '59 14 31 12 *' # 매년 12월 31일 밤 11:59 KST 기준
  workflow_dispatch:

jobs:
  trigger_webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Call Make Webhook for Yearly
      run: |
        curl -X POST "${{ secrets.MAKE_WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          -d '{"type": "year"}'